version: "3"

services:
  strapi:
    build: .
    container_name: fanruan_cms
    restart: always
    ports:
      - "1337:1337"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public:/app/public
      - ./.env:/app/.env

  db:
    image: postgres:16
    container_name: fanruan-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data