version: "3"

services:
  strapi:
    build: .
    container_name: fanruan_cms
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public:/app/public
      - ./.env:/app/.env
